### ISSUE TITLE
Environment issues

### ISSUE THREAD

**Issue by jaypatravali** [lizhou-cs/JointNLT#9]
I get this following error running inference on OTB sequences dataset.

`Couldn't load custom C++ ops. This can happen if your PyTorch and torchvision versions are incompatible, or if you had errors while compiling torchvision from source. For further information on the compatible versions, check https://github.com/pytorch/vision#installation for the compatibility matrix. Please check your PyTorch version with torch.__version__ and your torchvision version with torchvision.__version__ and verify if they are compatible, and if not please reinstall torchvision so that it matches your PyTorch install.
Traceback (most recent call last):
  File "tracking/../lib/test/evaluation/running.py", line 138, in run_sequence
    output = tracker.run_sequence(seq, debug=debug)
  File "tracking/../lib/test/evaluation/tracker.py", line 88, in run_sequence
    output = self._track_sequence(tracker, seq, init_info)
  File "tracking/../lib/test/evaluation/tracker.py", line 143, in _track_sequence
    out = tracker.track(image, info)
  File "tracking/../lib/test/tracker/jointnlt.py", line 130, in track
    out_dict = self.network.forward_test(self.text_dict, self.template_dict, search_patch, temporal)
  File "tracking/../lib/models/JointNLT.py", line 196, in forward_test
    return self.forward_joint(text_src, text_mask, template_src, template_mask, search_src, search_mask, temporal)
  File "tracking/../lib/models/JointNLT.py", line 168, in forward_joint
    roi_feature = self.get_target_feature(search_tokens, pred_boxes)
  File "tracking/../lib/models/JointNLT.py", line 210, in get_target_feature
    target_roi_feature = self.roi(opt_feat, boxes)
  File "/anaconda/envs/joint/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/anaconda/envs/joint/lib/python3.7/site-packages/torchvision/ops/roi_align.py", line 86, in forward
    return roi_align(input, rois, self.output_size, self.spatial_scale, self.sampling_ratio, self.aligned)
  File "/anaconda/envs/joint/lib/python3.7/site-packages/torchvision/ops/roi_align.py", line 55, in roi_align
    _assert_has_ops()
  File "/anaconda/envs/joint/lib/python3.7/site-packages/torchvision/extension.py", line 34, in _assert_has_ops
    "Couldn't load custom C++ ops. This can happen if your PyTorch and "
RuntimeError: Couldn't load custom C++ ops. This can happen if your PyTorch and torchvision versions are incompatible, or if you had errors while compiling torchvision from source. For further information on the compatible versions, check https://github.com/pytorch/vision#installation for the compatibility matrix. Please check your PyTorch version with torch.__version__ and your torchvision version with torchvision.__version__ and verify if they are compatible, and if not please reinstall torchvision so that it matches your PyTorch install.`

I prepared a conda env with joint.yml. 
It had two issues, so I had to change their versions manually.

external=2.0 version doesn't exist.
clip=1.0

**Comment by lizhou-cs** [comment]
I apologize for the delay in responding. It appears that you encountered an issue when calling 'roi_align'. This may be due to a compatibility issue between PyTorch and torchvision. To resolve this, you will need to reinstall torchvision to ensure that it matches your PyTorch installation.

**Comment by jaypatravali** [comment]
Thank you! I have resolved it by using this wheel 

pip install torchvision-0.12.0+cu113-cp37-cp37m-linux_x86_64.whl
